### ISSUE TITLE
cmd.py will prevent pandas from loading properly

### ISSUE THREAD

**Issue by Lotayou** [AliaksandrSiarohin/pose-gan#10]
I've found that when running test.py the pandas package will not load properly because the configure file cmd.py seems to override the same-name file while loading pandas (pdb more precisely). 

Here's the detailed error output:
`
Using TensorFlow backend.
/home/vcl/anaconda3/lib/python3.6/importlib/_bootstrap.py:205: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    from conditional_gan import make_generator
  File "/backup/lingboyang/pose-gan/conditional_gan.py", line 1, in <module>
    from keras.models import Model, Input, Sequential
  File "/home/vcl/anaconda3/lib/python3.6/site-packages/keras/__init__.py", line 3, in <module>
    from . import utils
  File "/home/vcl/anaconda3/lib/python3.6/site-packages/keras/utils/__init__.py", line 6, in <module>
    from . import conv_utils
  File "/home/vcl/anaconda3/lib/python3.6/site-packages/keras/utils/conv_utils.py", line 9, in <module>
    from .. import backend as K
  File "/home/vcl/anaconda3/lib/python3.6/site-packages/keras/backend/__init__.py", line 89, in <module>
    from .tensorflow_backend import *
  File "/home/vcl/anaconda3/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 5, in <module>
    import tensorflow as tf
  File "/home/vcl/anaconda3/lib/python3.6/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/home/vcl/anaconda3/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 83, in <module>
    from tensorflow.python.estimator import estimator_lib as estimator
  File "/home/vcl/anaconda3/lib/python3.6/site-packages/tensorflow/python/estimator/estimator_lib.py", line 35, in <module>
    from tensorflow.python.estimator.inputs import inputs
  File "/home/vcl/anaconda3/lib/python3.6/site-packages/tensorflow/python/estimator/inputs/inputs.py", line 22, in <module>
    from tensorflow.python.estimator.inputs.numpy_io import numpy_input_fn
  File "/home/vcl/anaconda3/lib/python3.6/site-packages/tensorflow/python/estimator/inputs/numpy_io.py", line 22, in <module>
    from tensorflow.python.estimator.inputs.queues import feeding_functions
  File "/home/vcl/anaconda3/lib/python3.6/site-packages/tensorflow/python/estimator/inputs/queues/feeding_functions.py", line 40, in <module>
    import pandas as pd
  File "/home/vcl/anaconda3/lib/python3.6/site-packages/pandas/__init__.py", line 59, in <module>
    from pandas.util._tester import test
  File "/home/vcl/anaconda3/lib/python3.6/site-packages/pandas/util/_tester.py", line 11, in <module>
    import pytest
  File "/home/vcl/anaconda3/lib/python3.6/site-packages/pytest.py", line 14, in <module>
    from _pytest.debugging import pytestPDB as __pytestPDB
  File "/home/vcl/anaconda3/lib/python3.6/site-packages/_pytest/debugging.py", line 3, in <module>
    import pdb
  File "/home/vcl/anaconda3/lib/python3.6/pdb.py", line 136, in <module>
    class Pdb(bdb.Bdb, cmd.Cmd):
AttributeError: module 'cmd' has no attribute 'Cmd'
`

See [this link](https://stackoverflow.com/questions/22600262/attribute-error-cmd-module) for reference.
I'm going to replace every reference of `cmd` in your project to another name and see if that fixes this issue. I'll let you know of any progress.

**Comment by AliaksandrSiarohin** [comment]
I see you using python3.
I test with python2, so maybe you will discover bunch of different issues.
It is probably easier to install python2.

**Comment by Lotayou** [comment]
All right. By the way, changing the file name from `cmd.py` to `config.py` and fix all references fixes my issue. 

Issue solved.
