### ISSUE TITLE
Test.py ValueError: You are trying to load a weight file containing 37 layers into a model with 35 layers.

### ISSUE THREAD

**Issue by iblh** [AliaksandrSiarohin/pose-gan#16]
```
▶ python3 test.py --generator_checkpoint ./checkpoints/fasion/generator-warp-mask.h5
Using TensorFlow backend.
2018-10-03 14:40:22.584639: W tensorflow/core/framework/op_def_util.cc:346] Op BatchNormWithGlobalNormalization is deprecated. It will cease to work in GraphDef version 9. Use tf.nn.batch_normalization().
2018-10-03 14:40:23.051506: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Generate images...
Number of images: 32668
Number of pairs train: 263632
Number of pairs test: 12000
Traceback (most recent call last):
  File "test.py", line 152, in <module>
    test()
  File "test.py", line 118, in test
    generator.load_weights(args.generator_checkpoint)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/keras/engine/network.py", line 1166, in load_weights
    f, self.layers, reshape=reshape)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/keras/engine/saving.py", line 1030, in load_weights_from_hdf5_group
    str(len(filtered_layers)) + ' layers.')
ValueError: You are trying to load a weight file containing 37 layers into a model with 35 layers.
```

**Comment by AliaksandrSiarohin** [comment]
You should use this command.
`python3 test.py --generator_checkpoint ./checkpoints/fasion/generator-warp-mask.h5 --warp_skip mask`
Also please note, that I use python2 so the code is probably not working with python3.

**Comment by iblh** [comment]
> You should use this command.
> `python3 test.py --generator_checkpoint ./checkpoints/fasion/generator-warp-mask.h5 --warp_skip mask`
> Also please note, that I use python2 so the code is probably not working with python3.

Very thanks for your reply.

Python 3 can also run the program. 

I try to add `--warp_skip mask` after the command, it still has an error(`35 layers` turns to `31 layers`), no matter python3 or python2:

```
▶ python3 test.py --generator_checkpoint ./checkpoints/fasion/generator-warp-mask.h5 --warp_skip mask
Using TensorFlow backend.
2018-10-03 23:34:18.266463: W tensorflow/core/framework/op_def_util.cc:346] Op BatchNormWithGlobalNormalization is deprecated. It will cease to work in GraphDef version 9. Use tf.nn.batch_normalization().
2018-10-03 23:34:18.634346: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Generate images...
Number of images: 32668
Number of pairs train: 263632
Number of pairs test: 12000
Traceback (most recent call last):
  File "test.py", line 152, in <module>
    test()
  File "test.py", line 118, in test
    generator.load_weights(args.generator_checkpoint)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/keras/engine/network.py", line 1166, in load_weights
    f, self.layers, reshape=reshape)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/keras/engine/saving.py", line 1030, in load_weights_from_hdf5_group
    str(len(filtered_layers)) + ' layers.')
ValueError: You are trying to load a weight file containing 37 layers into a model with 31 layers.
```

**Comment by iblh** [comment]
BTW, I use the checkpoints which downloaded from https://yadi.sk/d/dxVvYxBw3QuUT9

**Comment by AliaksandrSiarohin** [comment]
Sorry, you should also specify the dataset.
python3 test.py --generator_checkpoint ./checkpoints/fasion/generator-warp-mask.h5 --warp_skip mask --dataset fashion
