### ISSUE TITLE
IOError: File data/market-pairs-train.csv does not exist

### ISSUE THREAD

**Issue by qiangqiangzhu** [AliaksandrSiarohin/pose-gan#21]
Hi，
I'm running train.py on Ubutu 16.04, below is the issue i am getting..

Traceback (most recent call last):
  File "train.py", line 32, in <module>
    main()
  File "train.py", line 24, in main
    dataset = PoseHMDataset(test_phase=False, **vars(args))
  File "/home/aibc/Documents/xiangmu/pose-gan/pose_dataset.py", line 27, in __init__
    self._pairs_file_train = pd.read_csv(kwargs['pairs_file_train'])
  File "/home/aibc/.local/lib/python2.7/site-packages/pandas/io/parsers.py", line 678, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/home/aibc/.local/lib/python2.7/site-packages/pandas/io/parsers.py", line 440, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/aibc/.local/lib/python2.7/site-packages/pandas/io/parsers.py", line 787, in __init__
    self._make_engine(self.engine)
  File "/home/aibc/.local/lib/python2.7/site-packages/pandas/io/parsers.py", line 1014, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/home/aibc/.local/lib/python2.7/site-packages/pandas/io/parsers.py", line 1708, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 384, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 695, in pandas._libs.parsers.TextReader._setup_parser_source
IOError: File data/market-pairs-train.csv does not exist

And I found that I can't find the file(market-pairs-train.csv) 
If you have time, can provide a download link
Thank you

**Comment by AliaksandrSiarohin** [comment]
Have you tried to run a script:
```
python create_pairs_dataset.py
```
