### ISSUE TITLE
error in training with warp_skip = mask / full

### ISSUE THREAD

**Issue by SaeedSaadatnejad** [AliaksandrSiarohin/pose-gan#28]
Hello,

When I want to train the model with the configs that you mentioned (warp_skip = mask or full) it gives me this error. I don't have such a  problem with the baseline i.e. using warp_skip=none.
Can you help?

Thanks

```
2019-03-18 20:09:27.117571: I tensorflow/core/kernels/cuda_solvers.cc:159] Creating CudaSolver handles for stream 0x5637fe29dc40
2019-03-18 20:09:27.477257: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at matrix_inverse_op.cc:191 : Internal: tensorflow/core/kernels/cuda_solvers.cc:803: cuBlas call failed status = 13

Traceback (most recent call last):
  File "train.py", line 29, in <module>
    main()
  File "train.py", line 26, in main
    trainer.train()
  File "Deformable_GAN_last_try/gan/train.py", line 106, in train
    self.train_one_epoch((((self.current_epoch + 1) % self.checkpoint_ratio == 0) or self.current_epoch==0))
  File "Deformable_GAN_last_try/gan/train.py", line 79, in train_one_epoch
    self.train_one_step(discriminator_loss_list, generator_loss_list)
  File "Deformable_GAN_last_try/gan/train.py", line 68, in train_one_step
    loss = self.generator_model.train_on_batch(generator_batch, np.zeros([self.batch_size]))
  File "venvs/p2tf_new/local/lib/python2.7/site-packages/keras/engine/training.py", line 1217, in train_on_batch
    outputs = self.train_function(ins)
  File "venvs/p2tf_new/local/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 2715, in __call__
    return self._call(inputs)
  File "venvs/p2tf_new/local/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 2675, in _call
    fetched = self._callable_fn(*array_vals)
  File "venvs/p2tf_new/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1439, in __call__
    run_metadata_ptr)
  File "venvs/p2tf_new/local/lib/python2.7/site-packages/tensorflow/python/framework/errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InternalError: tensorflow/core/kernels/cuda_solvers.cc:803: cuBlas call failed status = 13
         [[{{node training_1/Adam/gradients/model_1/affine_transform_layer_2/transform/ImageProjectiveTransformV2_grad/MatrixInverse}} = MatrixInverse[T=DT_FLOAT, _class=["loc:@train...ransformV2"], adjoint=false, _device="/job:localhost/replica:0/task:0/device:GPU:0"](training_1/Adam/gradients/model_1/affine_transform_layer_2/transform/ImageProjectiveTransformV2_grad/flat_transforms_to_matrices/Reshape_1)]]
         [[{{node loss/mul/_1251}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_7915_loss/mul", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]] 
```

**Comment by AliaksandrSiarohin** [comment]
What tensorflow version you are using?

**Comment by SaeedSaadatnejad** [comment]
1.12.0

**Comment by AliaksandrSiarohin** [comment]
You should try 1.5

**Comment by SaeedSaadatnejad** [comment]
I tried to install the version that you mentioned in the file: requirements.txt.
It gives me this error: 'ImportError: cannot import name Model'
in this line: 'from keras import Model'

As I found this is related to the keras version that you mentioned 2.0.8.
Should I upgrade to the new version? Did you use this version?


Why didn't you mention tensorflow-gpu==1.5 in the requirements.txt? Because it seems you are using the gpu-version.

Thanks

**Comment by AliaksandrSiarohin** [comment]
**Should I upgrade to the new version? Did you use this version?**
2.0.8 version of keras works for me.
**As I found this is related to the keras version that you mentioned 2.0.8.**
Can you provide the link?
**Why didn't you mention tensorflow-gpu==1.5 in the requirements.txt?**
I use `pip freeze` to obtain requirments.txt, if you compile tensorflow from source the record is stored as tesnsorflow==1.5.0

**Comment by SaeedSaadatnejad** [comment]
I upgraded the keras and it works now.
Thanks.

Now my problem is that the results of market are not as good as the trained model and they are blurry.
Training with your suggested command (full)
`CUDA_VISIBLE_DEVICES=0 python train.py --warp_skip mask --dataset market --l1_penalty_weight 0.01 --nn_loss_area_size 3 --batch_size 4 --content_loss_layer block1_conv2 --number_of_epochs 90`
and testing the trained model after 90 epochs
`CUDA_VISIBLE_DEVICES=0 python test.py --generator_checkpoint output/full/epoch_089_generator.h5 --dataset market --warp_skip mask --l1_penalty_weight 0.01 --nn_loss_area_size 3 --batch_size 4 --content_loss_layer block1_conv2`

it gives me these which are not similar to your results.
![1312_c1s5_060041_02 jpg_1312_c1s5_060091_02 jpg](https://user-images.githubusercontent.com/43005619/54678002-710adb00-4b04-11e9-8900-1cd3b72388c5.png)
![1488_c1s6_023021_02 jpg jpg_1488_c1s6_023071_05 jpg jpg](https://user-images.githubusercontent.com/43005619/54678093-b4654980-4b04-11e9-8f5a-7da7c5ffd6a8.png)

but if I use your pre-trained model
`CUDA_VISIBLE_DEVICES=0 python test.py --generator_checkpoint  .../market/generator-warp-maks-nn3-cl12.h5 --dataset market --warp_skip mask --l1_penalty_weight 0.01 --nn_loss_area_size 3 --batch_size 4 --content_loss_layer block1_conv2`
it gives
![1312_c1s5_060041_02 jpg_1312_c1s5_060091_02 jpg](https://user-images.githubusercontent.com/43005619/54678034-87b13200-4b04-11e9-8bf3-e4dec6bb91b0.png)
![1488_c1s6_023021_02 jpg jpg_1488_c1s6_023071_05 jpg jpg](https://user-images.githubusercontent.com/43005619/54678101-b929fd80-4b04-11e9-80b5-53df38436f0d.png)

**Comment by AliaksandrSiarohin** [comment]
Not sure what is the cause of this.
Can you send me the values of losses, that is printed during the training?

**Comment by SaeedSaadatnejad** [comment]
[log.txt](https://github.com/AliaksandrSiarohin/pose-gan/files/2991307/log.txt)

**Comment by AliaksandrSiarohin** [comment]
What samples you get during training? Can you send some image from `output` folder?

**Comment by SaeedSaadatnejad** [comment]
[full.zip](https://github.com/AliaksandrSiarohin/pose-gan/files/2992014/full.zip)

**Comment by AliaksandrSiarohin** [comment]
> Number of pairs train: 741
> Number of pairs test: 744

How you generate pairs files?

**Comment by SaeedSaadatnejad** [comment]
I was using an old version which was already saved. It took 1 pair per id.
Maybe that's the problem. Now I'm trying with
`python create_pairs_dataset.py`
which gives
```Using TensorFlow backend.
Compute pair dataset for train...
Number of pairs: 263632
Compute pair dataset for test...
Number of pairs: 12000
```
I'll train it again and let you know.
Thanks

**Comment by rohit-saharan** [comment]
> I upgraded the keras and it works now.
> Thanks.
> 
> Now my problem is that the results of market are not as good as the trained model and they are blurry.
> Training with your suggested command (full)
> `CUDA_VISIBLE_DEVICES=0 python train.py --warp_skip mask --dataset market --l1_penalty_weight 0.01 --nn_loss_area_size 3 --batch_size 4 --content_loss_layer block1_conv2 --number_of_epochs 90`
> and testing the trained model after 90 epochs
> `CUDA_VISIBLE_DEVICES=0 python test.py --generator_checkpoint output/full/epoch_089_generator.h5 --dataset market --warp_skip mask --l1_penalty_weight 0.01 --nn_loss_area_size 3 --batch_size 4 --content_loss_layer block1_conv2`
> 
> it gives me these which are not similar to your results.
> ![1312_c1s5_060041_02 jpg_1312_c1s5_060091_02 jpg](https://user-images.githubusercontent.com/43005619/54678002-710adb00-4b04-11e9-8900-1cd3b72388c5.png)
> ![1488_c1s6_023021_02 jpg jpg_1488_c1s6_023071_05 jpg jpg](https://user-images.githubusercontent.com/43005619/54678093-b4654980-4b04-11e9-8f5a-7da7c5ffd6a8.png)
> 
> but if I use your pre-trained model
> `CUDA_VISIBLE_DEVICES=0 python test.py --generator_checkpoint .../market/generator-warp-maks-nn3-cl12.h5 --dataset market --warp_skip mask --l1_penalty_weight 0.01 --nn_loss_area_size 3 --batch_size 4 --content_loss_layer block1_conv2`
> it gives
> ![1312_c1s5_060041_02 jpg_1312_c1s5_060091_02 jpg](https://user-images.githubusercontent.com/43005619/54678034-87b13200-4b04-11e9-8bf3-e4dec6bb91b0.png)
> ![1488_c1s6_023021_02 jpg jpg_1488_c1s6_023071_05 jpg jpg](https://user-images.githubusercontent.com/43005619/54678101-b929fd80-4b04-11e9-80b5-53df38436f0d.png)

Hey, any info on what version of keras you upgraded ?
