### ISSUE TITLE
problems when test checkpoint files

### ISSUE THREAD

**Issue by menyifang** [AliaksandrSiarohin/pose-gan#40]
Hi,
Thank you for your great work! I have encountered some inexplicable problems when using your checkpoints.
when I test in fashion dataset as:
run python test.py --generator_checkpoint ./checkpoints/generator-warp-mask-nn5-cl12.h5 --warp_skip mask
Have encountered the previous error：
"tensorflow.python.framework.errors_impl.InvalidArgumentError: input_1:0 is both fed and fetched."
Then I fix it by replacing line142 with ：
    outputs = [input_img] + input_pose + [out, output_pose] + bg_img + warp_in_disc
    outputs = [keras.layers.Lambda(lambda x: ktf.identity(x))(out) for out in outputs]
    return Model(inputs=[input_img] + input_pose + [output_img, output_pose] + bg_img + warp, outputs=outputs)

However, there is another new problem in the running process.
Traceback (most recent call last):
  File "/data00/home/menyifang/code/comparison/pose-gan/test.py", line 152, in <module>
    test()
  File "/data00/home/menyifang/code/comparison/pose-gan/test.py", line 119, in test
    input_images, target_images, generated_images, names = generate_images(dataset, generator, args.use_input_pose)
  File "/data00/home/menyifang/code/comparison/pose-gan/test.py", line 91, in generate_images
    out = generator.predict(batch)
  File "/data00/home/menyifang/anaconda3/envs/tfgpu/lib/python3.6/site-packages/keras/engine/training.py", line 1462, in predict
    callbacks=callbacks)
  File "/data00/home/menyifang/anaconda3/envs/tfgpu/lib/python3.6/site-packages/keras/engine/training_arrays.py", line 324, in predict_loop
    batch_outs = f(ins_batch)
  File "/data00/home/menyifang/anaconda3/envs/tfgpu/lib/python3.6/site-packages/tensorflow/python/keras/backend.py", line 3076, in __call__
    run_metadata=self.run_metadata)
  File "/data00/home/menyifang/anaconda3/envs/tfgpu/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1439, in __call__
    run_metadata_ptr)
  File "/data00/home/menyifang/anaconda3/envs/tfgpu/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: output dimensions must be positive
	 [[{{node affine_transform_layer_2/ResizeNearestNeighbor}}]]
	 [[{{node lambda_3/Identity}}]]

Is there an idea to solve this problem?
version I use: tf 1.13.1, keras 2.3.0

**Comment by AliaksandrSiarohin** [comment]
Never saw a problem like this. This happens for both market and fashion?
Have you tried to use 
keras==2.0.8
tensorflow==1.5.0 ?

**Comment by menyifang** [comment]
I created envs as yours (keras==2.0.8, tensorflow==1.5.0) and it was solved. Thank you!
