### ISSUE TITLE
Error while executing "create_pairs_dataset.py" file

### ISSUE THREAD

**Issue by gyawali9** [AliaksandrSiarohin/pose-gan#43]
roshan@roshan-Satellite-L855:~/Desktop/pose-gan$ python2 create_pairs_dataset.pyTraceback (most recent call last):
  File "create_pairs_dataset.py", line 1, in <module>
    import pandas as pd
  File "/home/roshan/.local/lib/python2.7/site-packages/pandas/__init__.py", line 19, in <module>
    "Missing required dependencies {0}".format(missing_dependencies))
ImportError: Missing required dependencies ['numpy']

**Comment by AliaksandrSiarohin** [comment]
Guess you do not have a numpy installed.
Check dependencies in requirements.txt
